### ISSUE TITLE
git pull failed with cannot create directory

### ISSUE THREAD

**Issue by fenglui** [zurutech/gans-from-theory-to-production#11]
remote: Total 36 (delta 1), reused 24 (delta 0), pack-reused 0
fatal: cannot create directory at '1. GAN: theory and applications': Invalid argument
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'

**Comment by EmanueleGhelfi** [comment]
Hi @fenglui, which OS is installed in your system?
Probably this issue is due to the special character ':' in the directory name that is not allowed in Windows.
We should manage to update the directories name.

**Comment by galeone** [comment]
@fenglui the issue should be fixed now. Please let me know if it works
