### ISSUE TITLE
Update the README.md

### ISSUE THREAD

**Issue by mr-ubik** [zurutech/gans-from-theory-to-production#13]
Update the README.md

- [x] Bump TF Version to 2.0
- [x] Bump Python Version to 3.7 
- [x] Add @iLeW and @EmanueleGhelfi to the **Authors**

**Comment by galeone** [comment]
- requirements file updated - just updating the readme.md that was missing
- No need the require python 3.7 as the minimum requirement, 3.6 is enough
- right
